locales:
  en:
    name: Romany Keyboards for Sweden
    description: >-
      Keyboards for the Romany languages of Sweden: Arli, Kalo, Kelderasch and
      Lovari.
  sv:
    name: Romska tangentbord för Sverige
    description: >-
      Tangentbord för de romska språken i Sverige: arli, kalo, kelderasch och
      lovari.
author: 'The Divvun Group, UiT Norgga árktalaš universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga árktalaš universitehta
