template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 20
template_sha = "dd5ba321303960f3235b05136da0d20f3d656b35"

[replacements]
__UND2C__ = "rom"
__UNDEFINED__ = "Romany"
__UND__ = "rom"
